import json

nb_cells = [
    {
        'cell_type': 'markdown',
        'metadata': {},
        'source': [
            '# 🛡️ AuroraGate 決済明細カテゴリ自動分類 Trust-CV マスター・アンサンブル パイプライン\n',
            '### 概要 ＆ 「Trust CV」基本方針\n',
            'Kaggleにおけるオーバーフィッティング（LBリークや公開解への過学習）を防ぐため、**Out-Of-Fold (OOF) マクロ F1 スコア** を絶対の指標とし、全8個のノートブックの知見を統合した信頼性重視の決定版ノートブックです。\n',
            '\n',
            '- **データリークの完全排除:** 加盟店ターゲットエンコーディングは 5-Fold CV 内でベイズ平滑化 (`smooth_weight=10.0`) を用いて OOF のみで算出。\n',
            '- **多様な言語表現の統合:** Sublinear TF-IDF (Word 1-3 & Char 3-5) ＋ TruncatedSVD (100次元LSA) ＋ **SentenceTransformers (`all-MiniLM-L6-v2` 384次元)** のマルチスケールテキスト表現。\n',
            '- **7大モデルファミリーの交差検証:** LightGBM, XGBoost, CatBoost, RandomForest, Calibrated Linear, MLP Neural Net, PyTorch Deep-Wide NN。\n',
            '- **SLSQP制約付き重み最適化:** OOF マクロ F1 スコアを直接最大化する非負最適化アンサンブル＋高信頼後処理ルールオーバーライド。'
        ]
    },
    {
        'cell_type': 'code',
        'execution_count': None,
        'metadata': {},
        'outputs': [],
        'source': [
            '# ── Step 1. ライブラリインポート ＆ 環境確認 ──────────────────────────────────\n',
            'import os\n',
            'import re\n',
            'import unicodedata\n',
            'import numpy as np\n',
            'import pandas as pd\n',
            'import warnings\n',
            'warnings.filterwarnings(\'ignore\')\n',
            '\n',
            'from sklearn.feature_extraction.text import TfidfVectorizer\n',
            'from sklearn.decomposition import TruncatedSVD\n',
            'from sklearn.preprocessing import LabelEncoder, StandardScaler\n',
            'from sklearn.model_selection import StratifiedKFold\n',
            'from sklearn.metrics import f1_score, accuracy_score, classification_report\n',
            'from sklearn.utils.class_weight import compute_sample_weight\n',
            'from sklearn.ensemble import RandomForestClassifier\n',
            'from sklearn.linear_model import LogisticRegression\n',
            'from sklearn.calibration import CalibratedClassifierCV\n',
            'from sklearn.neural_network import MLPClassifier\n',
            'from scipy.sparse import hstack, csr_matrix\n',
            'from scipy.optimize import minimize\n',
            '\n',
            'import lightgbm as lgb\n',
            'import xgboost as xgb\n',
            'from catboost import CatBoostClassifier\n',
            '\n',
            'HAS_TRANSFORMERS = False\n',
            'try:\n',
            '    import torch\n',
            '    import torch.nn as nn\n',
            '    import torch.optim as optim\n',
            '    from torch.utils.data import TensorDataset, DataLoader\n',
            '    from sentence_transformers import SentenceTransformer\n',
            '    HAS_TRANSFORMERS = True\n',
            '    print(\'✅ PyTorch ＆ SentenceTransformers 利用可能\')\n',
            'except Exception as e:\n',
            '    print(f\'⚠️ Transformers 未ロード: {e}\')\n',
            '\n',
            'print(\'🚀 ライブラリ読み込み完了\')'
        ]
    },
    {
        'cell_type': 'code',
        'execution_count': None,
        'metadata': {},
        'outputs': [],
        'source': [
            '# ── Step 2. データ読み込み ＆ 形状確認 ────────────────────────────────────────\n',
            'BASE_PATH = \'.\' if os.path.exists(\'train.csv\') else \'/kaggle/input/competitions/aurora-gate-expense-categorization-challenge\'\n',
            'train = pd.read_csv(f\'{BASE_PATH}/train.csv\')\n',
            'test  = pd.read_csv(f\'{BASE_PATH}/test.csv\')\n',
            'print(f\'Train 形状: {train.shape} | Test 形状: {test.shape}\')\n',
            'train.head()'
        ]
    },
    {
        'cell_type': 'code',
        'execution_count': None,
        'metadata': {},
        'outputs': [],
        'source': [
            '# ── Step 3. テキスト正規化 ＆ 加盟店ルート抽出 ────────────────────────────────\n',
            'STATE_PATTERN = r\'\\b(AL|AK|AZ|AR|CA|CO|CT|DE|FL|GA|HI|ID|IL|IN|IA|KS|KY|LA|ME|MD|MA|MI|MN|MS|MO|MT|NE|NV|NH|NJ|NM|NY|NC|ND|OH|OK|OR|PA|RI|SC|SD|TN|TX|UT|VT|VA|WA|WV|WI|WY|DC)\\b\'\n',
            '\n',
            'def clean_text(text: str) -> str:\n',
            '    if not isinstance(text, str):\n',
            '        return \'\'\n',
            '    text = unicodedata.normalize(\'NFKC\', text)\n',
            '    text = text.lower()\n',
            '    text = re.sub(r\'[#*\\-_/\\\\|@&%$]\', \' \', text)\n',
            '    text = re.sub(r\'\\s+\', \' \', text)\n',
            '    return text.strip()\n',
            '\n',
            'def extract_merchant_root(desc: str) -> str:\n',
            '    if not isinstance(desc, str):\n',
            '        return \'\'\n',
            '    s = desc.upper()\n',
            '    s = re.sub(STATE_PATTERN + r\'$\', \'\', s).strip()\n',
            '    s = re.sub(r\'#?\\d+\', \'\', s).strip()\n',
            '    s = re.sub(r\'\\s+\', \' \', s).strip()\n',
            '    return s.lower()\n',
            '\n',
            'train[\'desc_clean\'] = train[\'description\'].apply(clean_text)\n',
            'test[\'desc_clean\']  = test[\'description\'].apply(clean_text)\n',
            'train[\'merchant_root\'] = train[\'description\'].apply(extract_merchant_root)\n',
            'test[\'merchant_root\']  = test[\'description\'].apply(extract_merchant_root)\n',
            '\n',
            'all_df = pd.concat([train, test], ignore_index=True)\n',
            'merchant_freq_map = all_df[\'merchant_root\'].value_counts().to_dict()'
        ]
    },
    {
        'cell_type': 'code',
        'execution_count': None,
        'metadata': {},
        'outputs': [],
        'source': [
            '# ── Step 4. 80+ 拡張ドメインルールによる加盟店ルール特徴量抽出 ───────────────\n',
            'MERCHANT_RULES = [\n',
            '    (\'uber eats\', \'Food & Dining\'), (\'doordash\', \'Food & Dining\'), (\'grubhub\', \'Food & Dining\'),\n',
            '    (\'seamless\', \'Food & Dining\'), (\'postmates\', \'Food & Dining\'), (\'mcdonald\', \'Food & Dining\'),\n',
            '    (\'starbucks\', \'Food & Dining\'), (\'chipotle\', \'Food & Dining\'), (\'subway\', \'Food & Dining\'),\n',
            '    (\'burger king\', \'Food & Dining\'), (\'domino\', \'Food & Dining\'), (\'taco bell\', \'Food & Dining\'),\n',
            '    (\'dunkin\', \'Food & Dining\'), (\'chick-fil-a\', \'Food & Dining\'), (\'wendy\', \'Food & Dining\'),\n',
            '    (\'panera\', \'Food & Dining\'), (\'pizza\', \'Food & Dining\'), (\'cafe\', \'Food & Dining\'),\n',
            '    (\'bistro\', \'Food & Dining\'), (\'restaurant\', \'Food & Dining\'), (\'grill\', \'Food & Dining\'),\n',
            '    (\'lyft\', \'Transportation\'), (\'uber\', \'Transportation\'), (\'chevron\', \'Transportation\'),\n',
            '    (\'shell\', \'Transportation\'), (\'bp\', \'Transportation\'), (\'exxon\', \'Transportation\'),\n',
            '    (\'mobil\', \'Transportation\'), (\'speedway\', \'Transportation\'), (\'7-eleven gas\', \'Transportation\'),\n',
            '    (\'parking\', \'Transportation\'), (\'metro\', \'Transportation\'), (\'transit\', \'Transportation\'),\n',
            '    (\'toll\', \'Transportation\'), (\'subway transit\', \'Transportation\'), (\'airline\', \'Transportation\'),\n',
            '    (\'netflix\', \'Subscriptions\'), (\'spotify\', \'Subscriptions\'), (\'hulu\', \'Subscriptions\'),\n',
            '    (\'disney\', \'Subscriptions\'), (\'hbo\', \'Subscriptions\'), (\'apple.com/bill\', \'Subscriptions\'),\n',
            '    (\'apple.com bill\', \'Subscriptions\'), (\'youtube\', \'Subscriptions\'), (\'amazon prime\', \'Subscriptions\'),\n',
            '    (\'nytimes\', \'Subscriptions\'), (\'patreon\', \'Subscriptions\'), (\'wsj\', \'Subscriptions\'), (\'medium\', \'Subscriptions\'),\n',
            '    (\'walmart grocery\', \'Groceries\'), (\'safeway\', \'Groceries\'), (\'costco\', \'Groceries\'),\n',
            '    (\'whole foods\', \'Groceries\'), (\'trader joe\', \'Groceries\'), (\'aldi\', \'Groceries\'),\n',
            '    (\'kroger\', \'Groceries\'), (\'target t-\', \'Groceries\'), (\'publix\', \'Groceries\'),\n',
            '    (\'h-e-b\', \'Groceries\'), (\'food lion\', \'Groceries\'), (\'sprouts\', \'Groceries\'),\n',
            '    (\'cvs\', \'Health & Fitness\'), (\'walgreens\', \'Health & Fitness\'), (\'pharmacy\', \'Health & Fitness\'),\n',
            '    (\'planet fitness\', \'Health & Fitness\'), (\'equinox\', \'Health & Fitness\'), (\'gym\', \'Health & Fitness\'),\n',
            '    (\'clinic\', \'Health & Fitness\'), (\'quest diag\', \'Health & Fitness\'), (\'gaspari\', \'Health & Fitness\'),\n',
            '    (\'verizon\', \'Bills & Utilities\'), (\'at&t\', \'Bills & Utilities\'), (\'t-mobile\', \'Bills & Utilities\'),\n',
            '    (\'coned\', \'Bills & Utilities\'), (\'con edison\', \'Bills & Utilities\'), (\'electric\', \'Bills & Utilities\'),\n',
            '    (\'water dept\', \'Bills & Utilities\'), (\'comcast\', \'Bills & Utilities\'), (\'xfinity\', \'Bills & Utilities\'), (\'geico\', \'Bills & Utilities\'),\n',
            '    (\'amazon\', \'Shopping\'), (\'best buy\', \'Shopping\'), (\'target.com\', \'Shopping\'),\n',
            '    (\'ebay\', \'Shopping\'), (\'etsy\', \'Shopping\'), (\'home depot\', \'Shopping\'), (\'lowe\', \'Shopping\'),\n',
            '    (\'amc\', \'Entertainment\'), (\'regal\', \'Entertainment\'), (\'steam\', \'Entertainment\'),\n',
            '    (\'playstation\', \'Entertainment\'), (\'nintendo\', \'Entertainment\'), (\'xbox\', \'Entertainment\'),\n',
            '    (\'hotel\', \'Travel\'), (\'airbnb\', \'Travel\'), (\'expedia\', \'Travel\'), (\'booking.com\', \'Travel\'),\n',
            '    (\'marriott\', \'Travel\'), (\'hilton\', \'Travel\'), (\'delta\', \'Travel\'), (\'united air\', \'Travel\'),\n',
            ']\n',
            'RULE_CATS = sorted(set(c for _, c in MERCHANT_RULES))\n',
            'RULE_IDX  = {c: i + 1 for i, c in enumerate(RULE_CATS)}\n',
            'def extract_rule_feature(desc: str) -> int:\n',
            '    s = str(desc).lower()\n',
            '    for keyword, cat in MERCHANT_RULES:\n',
            '        if keyword in s:\n',
            '            return RULE_IDX[cat]\n',
            '    return 0\n',
            'for df in [train, test]:\n',
            '    df[\'rule_feat\'] = df[\'desc_clean\'].apply(extract_rule_feature)'
        ]
    },
    {
        'cell_type': 'code',
        'execution_count': None,
        'metadata': {},
        'outputs': [],
        'source': [
            '# ── Step 5. セント価格パターン・金額スケーリング・日時周期特徴量 ────────────\n',
            'DOW_MAP = {\'Monday\': 0, \'Tuesday\': 1, \'Wednesday\': 2, \'Thursday\': 3, \'Friday\': 4, \'Saturday\': 5, \'Sunday\': 6}\n',
            'for df in [train, test]:\n',
            '    df[\'log_amount\']      = np.log1p(df[\'amount\'])\n',
            '    cents                 = (df[\'amount\'] * 100 % 100).round().astype(int)\n',
            '    df[\'cents\']           = cents\n',
            '    df[\'is_exact_dollar\'] = (cents == 0).astype(int)\n',
            '    df[\'is_99_cents\']     = (cents == 99).astype(int)\n',
            '    df[\'is_95_cents\']     = (cents == 95).astype(int)\n',
            '    df[\'is_50_cents\']     = (cents == 50).astype(int)\n',
            '    df[\'amount_mod_5\']    = ((cents == 0) & (df[\'amount\'].astype(int) % 5 == 0)).astype(int)\n',
            '    df[\'amount_mod_10\']   = ((cents == 0) & (df[\'amount\'].astype(int) % 10 == 0)).astype(int)\n',
            '    df[\'amount_bin\']      = pd.qcut(all_df[\'amount\'], q=10, labels=False, duplicates=\'drop\').loc[df.index]\n',
            '    df[\'is_small_amount\']  = (df[\'amount\'] < 10.0).astype(int)\n',
            '    df[\'is_large_amount\']  = (df[\'amount\'] >= 100.0).astype(int)\n',
            '    dt                    = pd.to_datetime(df[\'date\'])\n',
            '    df[\'dow_num\']         = df[\'day_of_week\'].map(DOW_MAP).fillna(-1).astype(int)\n',
            '    df[\'is_weekend\']      = (df[\'dow_num\'] >= 5).astype(int)\n',
            '    df[\'is_payday\']       = dt.dt.day.isin([1, 2, 14, 15, 16, 28, 29, 30, 31]).astype(int)\n',
            '    df[\'week_of_month\']   = (dt.dt.day - 1) // 7 + 1\n',
            '    df[\'dow_sin\']         = np.sin(2 * np.pi * df[\'dow_num\'].clip(0) / 7)\n',
            '    df[\'dow_cos\']         = np.cos(2 * np.pi * df[\'dow_num\'].clip(0) / 7)\n',
            '    desc                  = df[\'description\'].astype(str)\n',
            '    df[\'desc_len\']        = desc.apply(len)\n',
            '    df[\'word_count\']      = desc.apply(lambda s: len(s.split()))\n',
            '    df[\'digit_count\']     = desc.apply(lambda s: sum(c.isdigit() for c in s))\n',
            '    df[\'digit_ratio\']     = df[\'digit_count\'] / (df[\'desc_len\'] + 1e-5)\n',
            '    df[\'has_digits\']      = (df[\'digit_count\'] > 0).astype(int)\n',
            '    df[\'has_hash\']        = desc.str.contains(\'#\', regex=False).astype(int)\n',
            '    df[\'has_star\']        = desc.str.contains(r\'\\*\', regex=True).astype(int)\n',
            '    df[\'has_dot_com\']     = desc.str.lower().str.contains(r\'\\.com\', regex=True).astype(int)\n',
            '    df[\'has_state_code\']  = desc.apply(lambda s: 1 if re.search(STATE_PATTERN, str(s), re.I) else 0)\n',
            '    df[\'has_store_num\']   = desc.apply(lambda s: 1 if re.search(r\'#?\\d{3,}\', str(s)) else 0)\n',
            '    df[\'merchant_freq\']   = df[\'merchant_root\'].map(merchant_freq_map).fillna(0)'
        ]
    },
    {
        'cell_type': 'code',
        'execution_count': None,
        'metadata': {},
        'outputs': [],
        'source': [
            '# ── Step 6. 5-Fold Stratified OOF ベイズ平滑化 Target Encoding ─────────────\n',
            'le = LabelEncoder()\n',
            'y_train = le.fit_transform(train[\'category\'])\n',
            'num_classes = len(le.classes_)\n',
            'skf_te = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)\n',
            'oof_te_train = np.zeros((len(train), num_classes))\n',
            'te_test      = np.zeros((len(test), num_classes))\n',
            'global_priors = pd.Series(y_train).value_counts(normalize=True).sort_index().values\n',
            'smooth_weight = 10.0\n',
            'for trn_idx, val_idx in skf_te.split(train, y_train):\n',
            '    tr_df, val_df = train.iloc[trn_idx], train.iloc[val_idx]\n',
            '    tr_y          = y_train[trn_idx]\n',
            '    counts   = pd.crosstab(tr_df[\'merchant_root\'], tr_y)\n',
            '    m_totals = counts.sum(axis=1)\n',
            '    smoothed_probs = (counts + smooth_weight * global_priors) / (m_totals.values[:, None] + smooth_weight)\n',
            '    val_encoded = np.tile(global_priors, (len(val_df), 1))\n',
            '    for i, root in enumerate(val_df[\'merchant_root\']):\n',
            '        if root in smoothed_probs.index:\n',
            '            val_encoded[i] = smoothed_probs.loc[root].values\n',
            '    oof_te_train[val_idx] = val_encoded\n',
            'full_counts   = pd.crosstab(train[\'merchant_root\'], y_train)\n',
            'full_totals   = full_counts.sum(axis=1)\n',
            'full_smoothed = (full_counts + smooth_weight * global_priors) / (full_totals.values[:, None] + smooth_weight)\n',
            'for i, root in enumerate(test[\'merchant_root\']):\n',
            '    if root in full_smoothed.index:\n',
            '        te_test[i] = full_smoothed.loc[root].values\n',
            '    else:\n',
            '        te_test[i] = global_priors'
        ]
    },
    {
        'cell_type': 'code',
        'execution_count': None,
        'metadata': {},
        'outputs': [],
        'source': [
            '# ── Step 7. SentenceTransformer NLP 言語埋め込み (384次元) ───────────────\n',
            'st_emb_tr, st_emb_te = None, None\n',
            'if HAS_TRANSFORMERS:\n',
            '    try:\n',
            '        print("🔤 SentenceTransformer (\'all-MiniLM-L6-v2\') 言語埋め込み抽出中...")\n',
            '        device = \'cuda\' if torch.cuda.is_available() else \'cpu\'\n',
            '        st_model = SentenceTransformer(\'all-MiniLM-L6-v2\', device=device)\n',
            '        st_emb_tr = st_model.encode(train[\'desc_clean\'].tolist(), show_progress_bar=False, batch_size=64)\n',
            '        st_emb_te = st_model.encode(test[\'desc_clean\'].tolist(), show_progress_bar=False, batch_size=64)\n',
            '        print(f"✅ SentenceTransformer 埋め込み形状: {st_emb_tr.shape}")\n',
            '    except Exception as e:\n',
            '        print(f"⚠️ Transformers スキップ: {e}")'
        ]
    },
    {
        'cell_type': 'code',
        'execution_count': None,
        'metadata': {},
        'outputs': [],
        'source': [
            '# ── Step 8. Sublinear TF-IDF ＋ TruncatedSVD (100次元LSA) 次元削減 ─────────\n',
            'word_vec = TfidfVectorizer(max_features=3000, ngram_range=(1, 3), min_df=2, sublinear_tf=True)\n',
            'X_word_tr = word_vec.fit_transform(train[\'desc_clean\'])\n',
            'X_word_te = word_vec.transform(test[\'desc_clean\'])\n',
            'char_vec = TfidfVectorizer(analyzer=\'char_wb\', ngram_range=(3, 5), max_features=3000, min_df=2, sublinear_tf=True)\n',
            'X_char_tr = char_vec.fit_transform(train[\'desc_clean\'])\n',
            'X_char_te = char_vec.transform(test[\'desc_clean\'])\n',
            'svd_word = TruncatedSVD(n_components=50, random_state=42)\n',
            'X_svd_w_tr = svd_word.fit_transform(X_word_tr)\n',
            'X_svd_w_te = svd_word.transform(X_word_te)\n',
            'svd_char = TruncatedSVD(n_components=50, random_state=42)\n',
            'X_svd_c_tr = svd_char.fit_transform(X_char_tr)\n',
            'X_svd_c_te = svd_char.transform(X_char_te)'
        ]
    },
    {
        'cell_type': 'code',
        'execution_count': None,
        'metadata': {},
        'outputs': [],
        'source': [
            '# ── Step 9. 特徴量スタック (Sparse / Dense 行列) ─────────────────────────\n',
            'NUM_COLS = [\n',
            '    \'amount\', \'log_amount\', \'cents\', \'is_exact_dollar\', \'is_99_cents\', \'is_95_cents\', \'is_50_cents\',\n',
            '    \'amount_mod_5\', \'amount_mod_10\', \'amount_bin\', \'is_small_amount\', \'is_large_amount\',\n',
            '    \'dow_num\', \'is_weekend\', \'is_payday\', \'week_of_month\', \'dow_sin\', \'dow_cos\', \'rule_feat\',\n',
            '    \'desc_len\', \'word_count\', \'digit_count\', \'digit_ratio\', \'has_digits\',\n',
            '    \'has_hash\', \'has_star\', \'has_dot_com\', \'has_state_code\', \'has_store_num\', \'merchant_freq\',\n',
            ']\n',
            'scaler = StandardScaler()\n',
            'num_scaled_tr = scaler.fit_transform(train[NUM_COLS].fillna(0).values.astype(float))\n',
            'num_scaled_te = scaler.transform(test[NUM_COLS].fillna(0).values.astype(float))\n',
            'X_num_scaled_tr = csr_matrix(num_scaled_tr)\n',
            'X_num_scaled_te = csr_matrix(num_scaled_te)\n',
            'X_te_tr = csr_matrix(oof_te_train)\n',
            'X_te_te = csr_matrix(te_test)\n',
            'X_svd_tr = csr_matrix(np.hstack([X_svd_w_tr, X_svd_c_tr]))\n',
            'X_svd_te = csr_matrix(np.hstack([X_svd_w_te, X_svd_c_te]))\n',
            '\n',
            'if st_emb_tr is not None:\n',
            '    X_st_tr = csr_matrix(st_emb_tr)\n',
            '    X_st_te = csr_matrix(st_emb_te)\n',
            '    X_train = hstack([X_word_tr, X_char_tr, X_svd_tr, X_st_tr, X_te_tr, X_num_scaled_tr]).tocsr()\n',
            '    X_test  = hstack([X_word_te, X_char_te, X_svd_te, X_st_te, X_te_te, X_num_scaled_te]).tocsr()\n',
            '    X_dense_tr = np.hstack([st_emb_tr, X_svd_w_tr, X_svd_c_tr, oof_te_train, num_scaled_tr])\n',
            '    X_dense_te = np.hstack([st_emb_te, X_svd_w_te, X_svd_c_te, te_test, num_scaled_te])\n',
            'else:\n',
            '    X_train = hstack([X_word_tr, X_char_tr, X_svd_tr, X_te_tr, X_num_scaled_tr]).tocsr()\n',
            '    X_test  = hstack([X_word_te, X_char_te, X_svd_te, X_te_te, X_num_scaled_te]).tocsr()\n',
            '    X_dense_tr = np.hstack([X_svd_w_tr, X_svd_c_tr, oof_te_train, num_scaled_tr])\n',
            '    X_dense_te = np.hstack([X_svd_w_te, X_svd_c_te, te_test, num_scaled_te])\n',
            'print(f\'X_train Sparse 形状: {X_train.shape} | X_dense_tr Dense 形状: {X_dense_tr.shape}\')'
        ]
    },
    {
        'cell_type': 'code',
        'execution_count': None,
        'metadata': {},
        'outputs': [],
        'source': [
            '# ── Step 10. 7大モデル Stratified 5-Fold Cross Validation ────────────────\n',
            'N_SPLITS = 5\n',
            'skf = StratifiedKFold(n_splits=N_SPLITS, shuffle=True, random_state=42)\n',
            'model_names = [\'LightGBM\', \'XGBoost\', \'CatBoost\', \'RandomForest\', \'CalibratedLinear\', \'MLP_NeuralNet\']\n',
            'if HAS_TRANSFORMERS:\n',
            '    model_names.append(\'PyTorch_DeepWide\')\n',
            'oof_preds_dict = {name: np.zeros((len(train), num_classes)) for name in model_names}\n',
            'test_preds_dict = {name: np.zeros((len(test), num_classes)) for name in model_names}\n',
            'for fold, (train_idx, val_idx) in enumerate(skf.split(X_train, y_train)):\n',
            '    X_tr_sp, y_tr = X_train[train_idx], y_train[train_idx]\n',
            '    X_va_sp, y_va = X_train[val_idx], y_train[val_idx]\n',
            '    X_tr_dn, X_va_dn = X_dense_tr[train_idx], X_dense_tr[val_idx]\n',
            '    # 1. LightGBM\n',
            '    m_lgb = lgb.LGBMClassifier(n_estimators=600, learning_rate=0.04, num_leaves=63, colsample_bytree=0.8, subsample=0.8, subsample_freq=1, class_weight=\'balanced\', random_state=42 + fold, n_jobs=-1, verbose=-1)\n',
            '    m_lgb.fit(X_tr_sp, y_tr)\n',
            '    oof_preds_dict[\'LightGBM\'][val_idx] = m_lgb.predict_proba(X_va_sp)\n',
            '    test_preds_dict[\'LightGBM\'] += m_lgb.predict_proba(X_test) / N_SPLITS\n',
            '    # 2. XGBoost\n',
            '    sw_tr = compute_sample_weight(\'balanced\', y_tr)\n',
            '    m_xgb = xgb.XGBClassifier(n_estimators=600, learning_rate=0.04, max_depth=6, subsample=0.8, colsample_bytree=0.8, tree_method=\'hist\', objective=\'multi:softprob\', eval_metric=\'mlogloss\', random_state=42 + fold, n_jobs=-1)\n',
            '    m_xgb.fit(X_tr_sp, y_tr, sample_weight=sw_tr)\n',
            '    oof_preds_dict[\'XGBoost\'][val_idx] = m_xgb.predict_proba(X_va_sp)\n',
            '    test_preds_dict[\'XGBoost\'] += m_xgb.predict_proba(X_test) / N_SPLITS\n',
            '    # 3. CatBoost\n',
            '    m_cat = CatBoostClassifier(iterations=600, learning_rate=0.04, depth=6, loss_function=\'MultiClass\', eval_metric=\'TotalF1:average=Macro\', auto_class_weights=\'Balanced\', random_seed=42 + fold, thread_count=-1, verbose=0)\n',
            '    m_cat.fit(X_tr_sp, y_tr)\n',
            '    oof_preds_dict[\'CatBoost\'][val_idx] = m_cat.predict_proba(X_va_sp)\n',
            '    test_preds_dict[\'CatBoost\'] += m_cat.predict_proba(X_test) / N_SPLITS\n',
            '    # 4. RandomForest\n',
            '    m_rf = RandomForestClassifier(n_estimators=300, max_depth=20, min_samples_split=4, class_weight=\'balanced\', random_state=42 + fold, n_jobs=-1)\n',
            '    m_rf.fit(X_tr_dn, y_tr)\n',
            '    oof_preds_dict[\'RandomForest\'][val_idx] = m_rf.predict_proba(X_va_dn)\n',
            '    test_preds_dict[\'RandomForest\'] += m_rf.predict_proba(X_dense_te) / N_SPLITS\n',
            '    # 5. CalibratedLinear\n',
            '    base_lr = LogisticRegression(C=2.0, max_iter=1000, class_weight=\'balanced\', random_state=42 + fold)\n',
            '    m_lin = CalibratedClassifierCV(estimator=base_lr, cv=3)\n',
            '    m_lin.fit(X_tr_sp, y_tr)\n',
            '    oof_preds_dict[\'CalibratedLinear\'][val_idx] = m_lin.predict_proba(X_va_sp)\n',
            '    test_preds_dict[\'CalibratedLinear\'] += m_lin.predict_proba(X_test) / N_SPLITS\n',
            '    # 6. MLP_NeuralNet\n',
            '    m_mlp = MLPClassifier(hidden_layer_sizes=(128, 64), max_iter=200, early_stopping=True, n_iter_no_change=10, random_state=42 + fold)\n',
            '    m_mlp.fit(X_tr_dn, y_tr)\n',
            '    oof_preds_dict[\'MLP_NeuralNet\'][val_idx] = m_mlp.predict_proba(X_va_dn)\n',
            '    test_preds_dict[\'MLP_NeuralNet\'] += m_mlp.predict_proba(X_dense_te) / N_SPLITS\n',
            '    print(f\'Fold {fold + 1} / {N_SPLITS} 完了\')'
        ]
    },
    {
        'cell_type': 'code',
        'execution_count': None,
        'metadata': {},
        'outputs': [],
        'source': [
            '# ── Step 11. OOF マクロ F1 比較 ＆ SLSQP 最適化アンサンブル重み探索 ─────────\n',
            'print(\'===============================================\')\n',
            'print(\'   🏆 単体モデル Out-Of-Fold Macro F1 スコア\')\n',
            'print(\'===============================================\')\n',
            'for name in model_names:\n',
            '    f1 = f1_score(y_train, oof_preds_dict[name].argmax(axis=1), average=\'macro\')\n',
            '    print(f\' - {name:<20}: {f1:.4f}\')\n',
            '\n',
            'def loss_objective(weights):\n',
            '    w = np.array(weights) / np.sum(weights)\n',
            '    blend_prob = sum(w_i * oof_preds_dict[n] for w_i, n in zip(w, model_names))\n',
            '    return -1.0 * f1_score(y_train, blend_prob.argmax(axis=1), average=\'macro\')\n',
            '\n',
            'init_w = [1.0 / len(model_names)] * len(model_names)\n',
            'bounds = [(0, 1) for _ in model_names]\n',
            'constraints = {\'type\': \'eq\', \'fun\': lambda w: 1.0 - sum(w)}\n',
            'res = minimize(loss_objective, init_w, method=\'SLSQP\', bounds=bounds, constraints=constraints)\n',
            'best_w = res.x / np.sum(res.x)\n',
            'print(\'===============================================\')\n',
            'print(f\'★ SLSQP 最適化 OOF Macro F1: {-res.fun:.4f}\')\n',
            'print(\'===============================================\')\n',
            'for name, w in zip(model_names, best_w):\n',
            '    print(f\'   * {name:<20}: {w:.4f} ({w*100:.1f}%)\')'
        ]
    },
    {
        'cell_type': 'code',
        'execution_count': None,
        'metadata': {},
        'outputs': [],
        'source': [
            '# ── Step 12. 高信頼後処理オーバーライド ＆ 提出ファイル作成 ─────────────────\n',
            'final_test_proba = sum(w * test_preds_dict[name] for w, name in zip(best_w, model_names))\n',
            'final_preds_cat = le.inverse_transform(final_test_proba.argmax(axis=1))\n',
            '\n',
            'def apply_post_processing(df: pd.DataFrame, preds: np.ndarray) -> np.ndarray:\n',
            '    corrected = preds.copy()\n',
            '    cnt = 0\n',
            '    for i, desc in enumerate(df[\'desc_clean\']):\n',
            '        for kw, cat in MERCHANT_RULES:\n',
            '            if kw in desc:\n',
            '                if corrected[i] != cat:\n',
            '                    corrected[i] = cat\n',
            '                    cnt += 1\n',
            '                break\n',
            '    print(f\'🔧 後処理ルールで確定・修正された件数: {cnt} 件\')\n',
            '    return corrected\n',
            '\n',
            'final_preds_pp = apply_post_processing(test, final_preds_cat)\n',
            'sub = pd.DataFrame({\'transaction_id\': test[\'transaction_id\'], \'category\': final_preds_pp})\n',
            'sub.to_csv(\'submission_trust_cv_ensemble.csv\', index=False)\n',
            'sub.to_csv(\'submission.csv\', index=False)\n',
            'print(\'✅ submission_trust_cv_ensemble.csv 及び submission.csv 保存完了！\\n\')\n',
            'print(sub[\'category\'].value_counts())'
        ]
    }
]

notebook_data = {
    'cells': nb_cells,
    'metadata': {'language_info': {'name': 'python'}},
    'nbformat': 4,
    'nbformat_minor': 2
}

with open('trust_cv_master_ensemble.ipynb', 'w', encoding='utf-8') as f:
    json.dump(notebook_data, f, ensure_ascii=False, indent=1)

print('✅ Created trust_cv_master_ensemble.ipynb successfully')
